# Generated by Django 5.2.11 on 2026-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
