# Generated by Django 5.2.11 on 2026-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userprofile_phone_userprofile_role_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
