# Generated by Django 5.2.11 on 2026-02-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='party',
            name='gst_number',
        ),
    ]
