# Generated by Django 5.2.11 on 2026-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_purchase_due_amount_alter_purchase_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
