# Generated by Django 5.2.11 on 2026-03-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_sale_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='per_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
