# Generated by Django 5.2.11 on 2026-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_fix_per_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='per_item_price',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
    ]
