# Generated by Django 5.2.11 on 2026-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_maximum_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='quantity_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal')], default='decimal', max_length=10),
        ),
    ]
