# Generated by Django 5.2.11 on 2026-03-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_unit_quantity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quantity_type',
        ),
    ]
