# Generated by Django 5.2.11 on 2026-03-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_passwordchangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChangeRequest',
        ),
    ]
