# Generated by Django 5.2.11 on 2026-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_passwordchangerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
