# Generated by Django 5.2.11 on 2026-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_passwordchangerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Integer', 'Integer'), ('Decimal', 'Decimal')], default='Integer', max_length=10),
        ),
    ]
