# Generated by Django 5.2.11 on 2026-03-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_seed_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
