# Generated by Django 5.2.11 on 2026-03-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_product_sub_unit_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_products', to='inventory.unit'),
        ),
    ]
