# Generated by Django 5.2.11 on 2026-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_product_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many sub units = 1 base unit (e.g. 1 Bag = 40 Kg → 40)', max_digits=10),
        ),
    ]
